#!/bin/sh
# Originally generated by 'mxcli init'; the fetch step was rewritten to build
# from source. COMMIT THIS FILE.
#
# Run by the Claude Code SessionStart hook to make a fresh (or reaped and
# re-cloned) session ready to work: build mxcli if the binary is missing, then
# cache MxBuild + the runtime and provision the local database.
#
# The mxcli binary is git-ignored (~88 MB), so after an idle reap it is NOT in
# the fresh clone — which is exactly why this script rebuilds it rather than
# skipping when it is absent.
#
# WHY BUILD INSTEAD OF DOWNLOAD: this project tracks ako/mxcli main, not the
# mendixlabs/mxcli nightly release that 'mxcli init' wires up by default. There
# is no published binary for this fork, so the only way to reproduce the same
# mxcli in a fresh session is to build it. Expect ~2-4 minutes on a cold start.
#
# HEADS UP: re-running a bare 'mxcli init' OVERWRITES this file and restores the
# nightly download. If you do, restore this version from git. ('mxcli init
# --sync-skills', which the hook below runs on every start, returns before the
# hook-writing step and is therefore safe.)
#
# Override with MXCLI_REPO / MXCLI_REF if you need a different fork or branch.
set -e

MPR='RestLab.mpr'
MXCLI_REPO="${MXCLI_REPO:-https://github.com/ako/mxcli}"
MXCLI_REF="${MXCLI_REF:-main}"

# Pinned ANTLR toolchain — must match mdl/grammar/Makefile in the mxcli repo.
# The generated parser is not committed upstream, so 'make grammar' (and thus a
# JVM plus the antlr4 launcher) is a hard prerequisite of building at all.
ANTLR_TOOLS_VERSION=0.2.2
ANTLR_VERSION=4.13.2

if [ ! -x ./mxcli ]; then
  echo "mxcli not found — building ${MXCLI_REPO}@${MXCLI_REF} from source..."

  missing=''
  for tool in go make java git; do
    command -v "$tool" >/dev/null 2>&1 || missing="$missing $tool"
  done
  if [ -n "$missing" ]; then
    echo "Cannot build mxcli: missing required tool(s):$missing" >&2
    echo "Install them, or drop a prebuilt mxcli binary at ./mxcli." >&2
    exit 1
  fi

  src=$(mktemp -d)
  # shellcheck disable=SC2064
  trap "rm -rf '$src'" EXIT INT TERM

  git clone --depth 1 --branch "$MXCLI_REF" "$MXCLI_REPO" "$src/mxcli"

  # antlr4-tools downloads the pinned ANTLR jar on first run, so this needs
  # network and a JVM, not only Go. --break-system-packages is required on
  # Debian/Ubuntu images with an externally-managed Python.
  if ! command -v antlr4 >/dev/null 2>&1; then
    pip install --quiet --break-system-packages "antlr4-tools==${ANTLR_TOOLS_VERSION}" 2>/dev/null \
      || pip install --quiet "antlr4-tools==${ANTLR_TOOLS_VERSION}"
  fi
  PATH="$PATH:$HOME/.local/bin"
  export PATH
  ANTLR4_TOOLS_ANTLR_VERSION="$ANTLR_VERSION"
  export ANTLR4_TOOLS_ANTLR_VERSION

  # 'make build' == grammar + sync-all + completions. sync-all is load-bearing:
  # it embeds the skills and commands that 'mxcli init' later installs, so a
  # bare 'go build' would produce a binary that writes no skills.
  (cd "$src/mxcli" && make build)

  cp "$src/mxcli/bin/mxcli" ./mxcli
  chmod +x ./mxcli
  rm -rf "$src"
  trap - EXIT INT TERM
  echo "Built ./mxcli from ${MXCLI_REPO}@${MXCLI_REF}."
fi

# Keep .ai-context/skills/ in step with this binary. The skills are embedded in
# mxcli and written once by 'mxcli init', so upgrading the binary used to leave
# yesterday's guidance in place with no warning — and an agent reads stale
# guidance with the same confidence as current guidance. Quiet when already
# current; never fatal, since a skills refresh must not block the session.
./mxcli init --sync-skills . || true

exec ./mxcli run --local --setup --ensure-db -p "$MPR"
